import { PaymentSaleModel } from '../../sales-payment/models/payment-sale-model';
import { DocumentSaleDetailModel } from './document-detail-model';

export class DocumentSaleModel {
    id: number;
    docId: number;
    docReference: number;
    customerId: number;
    customerCode: string;
    customerName: string;
    customerRTN: string;
    customerAddress: string;
    payConditionId: number;
    payConditionDays: number;
    sellerId: number;
    sellerName: string;
    priceListId: number;
    docDate: Date;
    dueDate: Date;
    canceled: true;
    comment: string;
    correlativeId: number;
    reference: string;
    subTotal: number;
    tax: number;
    disccounts: number;
    discountsTotal: number;
    docTotal: number;
    docQty: number;
    whsCode: number;
    createBy: number;
    complete: true;
    detail: DocumentSaleDetailModel[];
    detailDto: DocumentSaleDetailModel[];
    payConditionName: string;
    createByName: string;
    whsName: string;
    taxSupplier: boolean;
    invoiceFiscalNo: string;
    establishment: string;
    point: string;
    type: string;
    cai: string;
    limitIssue: Date;
    authorizedRangeFrom: string;
    authorizedRangeTo: string;
    deiNumber: string;
    sumApplied: number;
    balance: number;
    payment: PaymentSaleModel
    paidToDate: number;
    uuid: string;
    offline: boolean;

    constructor(data?: DocumentSaleModel) {
        if (data != null) {
            this.docId = data.docId;
            this.customerId = data.customerId;
            this.customerCode = data.customerCode;
            this.customerName = data.customerName;
            this.payConditionId = data.payConditionId;
            this.payConditionDays = data.payConditionDays;
            this.docDate = data.docDate;
            this.dueDate = data.dueDate;
            this.canceled = data.canceled;
            this.sellerId = data.sellerId;
            this.comment = data.comment;
            this.reference = data.reference;
            this.subTotal = data.subTotal;
            this.tax = data.tax;
            this.disccounts = data.disccounts;
            this.discountsTotal = data.discountsTotal;
            this.docTotal = data.docTotal;
            this.docQty = data.docQty;
            this.whsCode = data.whsCode;
            this.createBy = data.createBy;
            this.complete = data.complete;
            this.detail = data.detail;
            this.invoiceFiscalNo = data.invoiceFiscalNo;
            this.establishment = data.establishment;
            this.point = data.point;
            this.type = data.type;
            this.cai = data.cai;
            this.limitIssue = data.limitIssue;
            this.authorizedRangeFrom = data.authorizedRangeFrom;
            this.authorizedRangeTo = data.authorizedRangeTo;
            this.uuid = data.uuid;
            this.offline = data.offline;
            return;
        }
        this.docId = this.docId;
        this.customerId = this.customerId;
        this.customerCode = this.customerCode;
        this.customerName = this.customerName;
        this.payConditionId = this.payConditionId;
        this.payConditionDays = this.payConditionDays;
        this.docDate = this.docDate;
        this.dueDate = this.dueDate;
        this.canceled = this.canceled;
        this.comment = this.comment;
        this.sellerId = this.sellerId;
        this.reference = this.reference;
        this.subTotal = this.subTotal;
        this.tax = this.tax;
        this.disccounts = this.disccounts;
        this.discountsTotal = this.discountsTotal;
        this.docTotal = this.docTotal;
        this.docQty = this.docQty;
        this.whsCode = this.whsCode;
        this.createBy = this.createBy;
        this.complete = this.complete;
        this.detail = [];
        this.invoiceFiscalNo = this.invoiceFiscalNo;
        this.establishment = this.establishment;
        this.point = this.point;
        this.type = this.type;
        this.cai = this.cai;
        this.limitIssue = this.limitIssue;
        this.authorizedRangeFrom = this.authorizedRangeFrom;
        this.authorizedRangeTo = this.authorizedRangeTo;
        this.uuid = this.uuid;
        this.offline = this.offline
        return;
    }
}
